# Generated by Django 4.0.3 on 2022-03-16 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_alter_item_quantity_alter_item_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='product',
        ),
    ]
