# Generated by Django 4.0.3 on 2022-03-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_rename_title_item_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, choices=[('KG', 'kg'), ('PCS', 'pcs'), ('PKGS', 'pkgs')], max_length=20, null=True),
        ),
    ]
