# Generated by Django 4.0.3 on 2022-03-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0004_alter_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('pcs', 'pcs'), ('pkgs', 'pkgs')], max_length=20, null=True),
        ),
    ]
