# Generated by Django 4.0.3 on 2022-03-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0005_alter_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('FV', 'fruits and vegetables'), ('MT', 'meat'), ('D', 'diary'), ('DG', 'dry goods'), ('ALC', 'alcohols'), ('MED', 'medicine'), ('PG', 'pet goods'), ('BG', 'baby goods'), ('DD', 'domestic detergents'), ('RCM', 'ready-cook meals'), ('H', 'hygiene'), ('CT', 'coffee & tea'), ('FF', 'frozen foods'), ('GT', 'garden and tinkering'), ('B', 'bread'), ('PV', 'preserves'), ('S', 'spices, sauces, additives'), ('FS', 'fishes and seafood'), ('SS', 'sweets and snacks'), ('F', 'fats'), ('WD', 'water and drinks'), ('DFN', 'dried fruit and nuts'), ('FH', 'fresh herbs'), ('CF', 'canned food'), ('O', 'other')], max_length=10),
        ),
    ]
