databases:
- engine: PG
  name: db
  num_nodes: 1
  size: basic-xxs
  version: "12"
envs:
- key: DISABLE_COLLECTSTATIC
  scope: RUN_AND_BUILD_TIME
  value: "1"
- key: DEBUG
  scope: RUN_AND_BUILD_TIME
  value: "0"
- key: DJANGO_ALLOWED_HOST
  scope: RUN_AND_BUILD_TIME
  value: .ondigitalocean.app
- key: DJANGO_SUPERUSER_EMAIL
  scope: RUN_AND_BUILD_TIME
  value: kamilwilczek@wp.pl
- key: DJANGO_SUPERUSER_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: kamil
- key: POSTGRES_DB
  scope: RUN_AND_BUILD_TIME
  value: ${db.DATABASE}
- key: POSTGRES_HOST
  scope: RUN_AND_BUILD_TIME
  value: ${db.HOSTNAME}
- key: POSTGRES_USER
  scope: RUN_AND_BUILD_TIME
  value: ${db.USERNAME}
- key: POSTGRES_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: ${db.PASSWORD}
- key: POSTGRES_PORT
  scope: RUN_AND_BUILD_TIME
  value: ${db.PORT}
- key: DJANGO_SECRET_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:Cfd1zUoB1I+jrADkclWkLPt6ejcONxEl:zaohTZuioEP1f9IIq3NsLoHDizyARQ==]
- key: AWS_ACCESS_KEY_ID
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:XlIUWeTCMCE2QIrpjT9uIpXFmvKof0zx:S/IWJS2VzUHtKcwcem7ivI0/Eg==]
- key: AWS_SECRET_ACCESS_KEY
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:XNuIBntLYb9eo4ARLtcOPByZKPKDtZSr:a6fLcYt8uT5UBhriJj+ja9Iz7A==]
- key: AWS_STORAGE_BUCKET_NAME
  scope: RUN_AND_BUILD_TIME
  value: td32
- key: DJANGO_SUPERUSER_PASSWORD
  scope: RUN_AND_BUILD_TIME
  type: SECRET
  value: EV[1:3Lq0n3JrxNjEA34PslT+Dx5DirxwjrNU:i+ySy6BfdKjl4/ds2FsEWnihc1Mgow==]
jobs:
- environment_slug: python
  github:
    branch: production-1
    deploy_on_push: true
    repo: KamilWilczek/Learning_Path
  instance_count: 1
  instance_size_slug: basic-xxs
  kind: PRE_DEPLOY
  name: django-migrate-job
  run_command: python manage.py migrate --noinput
  source_dir: /Raw/Python/td32/try-django/
name: td32-via-cli
region: fra
services:
- environment_slug: python
  github:
    branch: production-2
    deploy_on_push: true
    repo: KamilWilczek/Learning_Path
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: learning-path-raw-python-td-32-t
  routes:
  - path: /
  run_command: gunicorn --worker-tmp-dir /dev/shm trydjango.wsgi
  source_dir: /Raw/Python/td32/try-django/